// Single source of truth for all theme definitions
export const themes = {
  originalGreen: {
    name: 'Original Green',
    nameAr: 'الأخضر الأصلي',
    primary: '#003C34',
    primaryMedium: '#002B25',
    primaryDark: '#002520',
    accent: '#FFE29D',
    accentDark: '#D1955E',
    background: '#003C34',
    surface: '#002B25',
    text: '#FFE29D',
    textSecondary: '#D1955E',
  },
  goldOnWhite: {
    name: 'Gold on White',
    nameAr: 'الذهبي على الأبيض',
    primary: '#FFFFFF',
    primaryMedium: '#F5F5F5',
    primaryDark: '#E0E0E0',
    accent: '#D1955E',
    accentDark: '#B8804A',
    background: '#FFFFFF',
    surface: '#F5F5F5',
    text: '#D1955E',
    textSecondary: '#B8804A',
  },
  goldOnDark: {
    name: 'Gold on Dark',
    nameAr: 'الذهبي على الأسود',
    primary: '#1A1A1A',
    primaryMedium: '#2A2A2A',
    primaryDark: '#0A0A0A',
    accent: '#FFE29D',
    accentDark: '#D1955E',
    background: '#1A1A1A',
    surface: '#2A2A2A',
    text: '#FFE29D',
    textSecondary: '#D1955E',
  },
  paige: {
    name: 'Paige',
    nameAr: 'بيج',
    primary: '#F5F5DC',
    primaryMedium: '#E6E6D1',
    primaryDark: '#D4D4B8',
    accent: '#8B4513',
    accentDark: '#654321',
    background: '#F5F5DC',
    surface: '#E6E6D1',
    text: '#8B4513',
    textSecondary: '#654321',
  },
  chocolate: {
    name: 'Chocolate',
    nameAr: 'شوكولاتة',
    primary: '#8D6E63',
    primaryMedium: '#A1887F',
    primaryDark: '#5D4037',
    accent: '#FFF8E1',
    accentDark: '#F5E6A3',
    background: '#8D6E63',
    surface: '#A1887F',
    text: '#FFF8E1',
    textSecondary: '#F5E6A3',
  },
  lavender: {
    name: 'Lavender',
    nameAr: 'لافندر',
    primary: '#B39DDB',
    primaryMedium: '#C5B4E3',
    primaryDark: '#9575CD',
    accent: '#FFF9E6',
    accentDark: '#F0E6D2',
    background: '#B39DDB',
    surface: '#C5B4E3',
    text: '#FFF9E6',
    textSecondary: '#F0E6D2',
  }
};
