#!/bin/bash

# This is a file called "pre-install" in the root of the project

# if [[ "$EAS_BUILD_PLATFORM" == "android" ]]; then
# cat $GOOGLE_SERVICES_JSON > "android/app/google-services.json"
# cat android/app/google-services.json
# elif [[ "$EAS_BUILD_PLATFORM" == "ios" ]]; then
# cat $GOOGLE_SERVICES_PLIST > "ios/Zikr/GoogleService-Info.plist"
# fi
